### ISSUE TITLE
Can we cut a "3-2 stable" branch

### ISSUE THREAD

**Issue by dylnclrk** [vinsol-spree-contrib/spree_taxjar#30]
I'd love to use this with my Spree 3.2 app. Happy to help!

**Comment by pikender** [comment]
@dylnclrk [3-2-stable](https://github.com/vinsol-spree-contrib/spree_taxjar/tree/3-2-stable) branch created.

Use it and report the issues or use-cases to make it better :+1:

**Comment by dylnclrk** [comment]
Thanks y'all.
